apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fpultera/examplesArgoAndMore.git'
    path: apps/infra
    targetRevision: HEAD
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true